### PR TITLE
Optimize

### PR DESCRIPTION
**Pull request by egoist**
A bunch of changes to optimize the bundle files.

Previously, `DPlayer.min.js` is `126KB`, now `DPlayer.min.js` + `DPlayer.min.css` is `80KB`

### CODE REVIEW

**Comment by DIYgod** [comment]
Thanks, big lao!

**Comment by egoist** [comment]
btw, [this line](https://github.com/DIYgod/DPlayer/blob/master/src/DPlayer.js#L1) will be removed sinc webpack [strips all `console.log`](https://github.com/DIYgod/DPlayer/blob/master/webpack.config.js#L76) now, you can adjust it a bit to preserve that.

**Comment by egoist** [comment]
And the docs should also be updated since `DPlayer.min.css` is required now.

**Comment by DIYgod** [comment]
Done! Thanks!

**Pull request merged**
