### PR TITLE
fix #41

### LINKED ISSUE #41: 关闭弹幕之后再暂停播放，弹幕重新出现

### PR DESCRIPTION
**Pull request by guokeke**
issue #41

---
This change is [Reviewable](https://reviewable.io/reviews/diygod/dplayer/44)

### CODE REVIEW

**Comment by guokeke** [comment]
好寂寞, 谁来 review 下...

**Comment by Myer921** [comment]
@guokeke 月圆之夜 约吗？

**Comment by guokeke** [comment]
@Myer921 不约, 雾霾太重.

**Comment by DIYgod** [comment]
Thanks for your work, but it can be fixed easier, see: https://github.com/DIYgod/DPlayer/commit/e1a854285ec8c281d596fd6feafbbe506a5ce108

**Comment by guokeke** [comment]
well

**Pull request closed without merging**
